newb/apps/shop/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from newb.apps.shop import views
from newb.apps.shop.forms import AuthForm

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^shop/$', views.shop, name='shop'),
    url(r'^shop/checkout/(?P<id>[0-9]+)/$', views.shop_checkout, name='shop_checkout'),
    url(r'^shop/checkout/done/$', views.shop_checkout_done, name='shop_checkout_done'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='shop/login.html', authentication_form=AuthForm), name='login'),
    url(r'^authentication/$', views.authentication, name='authentication'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^account/$', views.account, name='account'),
    url(r'^contact/$', views.contact, name='contact'),
]

newb/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from newb import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('newb.apps.shop.urls', namespace='shop')),
    url('^', include('django.contrib.auth.urls')),  # keep at the end
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newb/apps/shop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField


class Genre(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nom')

    def __str__(self):
        return self.name


class Platform(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nom')
    constructor = models.CharField(max_length=100, null=True, blank=True, verbose_name='Constructeur')
    release_year = models.IntegerField(null=True, blank=True, verbose_name='Année de sortie')

    def __str__(self):
        return self.name


class Editor(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nom')

    def __str__(self):
        return self.name


class Developer(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nom')

    def __str__(self):
        return self.name


class VideoGame(models.Model):
    title = models.CharField(max_length=200, verbose_name='Titre')
    release_date = models.DateField(null=True, blank=True, verbose_name='Date de sortie')
    genres = models.ManyToManyField('Genre', verbose_name='Genres')
    platforms = models.ManyToManyField('Platform', verbose_name='Plateformes')
    editor = models.ForeignKey('Editor', verbose_name='Éditeur', null=True, blank=True)
    developer = models.ForeignKey('Developer', verbose_name='Développeur')
    picture = models.ImageField(upload_to="media/uploaded/img/shop/", null=True, blank=True, verbose_name='Jaquette')
    description = models.TextField(null=True, verbose_name='Description')
    price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Prix')

    def __str__(self):
        return self.title


# we add some informations at the user model which already exist on django
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=150, verbose_name='Adresse')
    postal_code = models.CharField(max_length=5, verbose_name='Code postal')
    city = models.CharField(max_length=100, verbose_name='Ville')
    country = models.CharField(max_length=75, verbose_name='Pays')
    phone = PhoneNumberField(verbose_name='Numéro de téléphone', help_text='Avec l\'indicatif du pays.')

    def __str__(self):
        return self.user


@receiver(post_save, sender=User)
def update_user_customer(sender, instance, created, **kwargs):
    if created:
        Customer.objects.create(user=instance)
    instance.customer.save()


class Contact(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nom')
    email = models.EmailField(verbose_name='Adresse email')
    subject = models.CharField(max_length=150, verbose_name='Sujet')
    message = models.TextField(verbose_name='Message')

    def __str__(self):
        return self.name + ' > [' + self.subject + "] " + self.message


class Order(models.Model):
    customer = models.ForeignKey("Customer")
    item = models.ForeignKey("VideoGame")

newb/apps/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from newb.apps.shop.models import Contact, Customer


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class CustomerRegisterForm(forms.ModelForm):

    class Meta:
        model = Customer
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(CustomerRegisterForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs.update({'placeholder': '+33'})
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class AuthForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(AuthForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

newb/apps/shop/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from newb.apps.shop.forms import CustomerRegisterForm, ContactForm, UserRegisterForm
from .models import VideoGame, Order


def index(request):
    context = {}
    return render(request, 'shop/index.html', context)


def shop(request):
    context = {
        'products': VideoGame.objects.all()
    }
    return render(request, 'shop/shop.html', context)


@login_required(login_url='/login/')
def shop_checkout(request, id):
    context = {
        'product': VideoGame.objects.get(id=id)
    }
    return render(request, 'shop/shop_checkout.html', context)


@login_required(login_url='/login/')
def shop_checkout_done(request):
    if request.method == 'POST':
        product = VideoGame.objects.get(id=request.POST.get("product-id"))
        order = Order(customer=request.user.customer, item=product)
        order.save()
        return redirect('shop:account')

    return redirect('shop:index')


def authentication(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)

    if user is not None:
        login(request, user)
        return HttpResponseRedirect('/')

    else:
        return HttpResponseRedirect('/login/')


@login_required(login_url='/login/')
def signout(request):
    logout(request)
    return HttpResponseRedirect('/')


@transaction.atomic
def register(request):
    if request.method == 'POST':
        user_form = UserRegisterForm(request.POST, prefix="user_form")
        customer_form = CustomerRegisterForm(request.POST, prefix="customer_form")

        if user_form.is_valid() and customer_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()

            user.customer.user_id = user.id
            user.customer.address = customer_form.cleaned_data.get('address')
            user.customer.postal_code = customer_form.cleaned_data.get('postal_code')
            user.customer.city = customer_form.cleaned_data.get('city')
            user.customer.country = customer_form.cleaned_data.get('country')
            user.customer.phone = customer_form.cleaned_data.get('phone')

            user.save()

            raw_password = user_form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')

    else:
        user_form = UserRegisterForm()
        user_form.prefix = "user_form"
        customer_form = CustomerRegisterForm()
        customer_form.prefix = "customer_form"

    context = {'user_form': user_form, 'customer_form': customer_form}
    return render(request, 'shop/register.html', context)


@login_required(login_url='/login/')
def account(request):
    context = {
        'orders': Order.objects.filter(customer=request.user.customer),
    }
    return render(request, 'shop/account.html', context)


def contact(request):
    context = {}
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            contact_instance = form.save()
            contact_instance.name = form.cleaned_data.get('name')
            contact_instance.subject = form.cleaned_data.get('subject')
            contact_instance.message = form.cleaned_data.get('message')
            contact_instance.save()

            if contact_instance is not None:
                context['success'] = "Message envoyé !"
                form = ContactForm()

    else:
        form = ContactForm()

    context['form'] = form
    return render(request, 'shop/contact.html', context)

newb/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'index.html', context)

newb/templates/base.html
{% load sekizai_tags static sass_tags %}
{% spaceless %}
<!doctype html>
<html>
    <head>
        <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
        <title>{% block title %}{% endblock title %} - Newb</title>

        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'fontello/css/fontello.css' %}">
        <link rel="stylesheet" type="text/css" href="{% sass_src 'css/base.scss' %}">
        {% endspaceless %}{% render_block 'css' %}{% spaceless %}
    </head>
    <body class="loading">
        <div class="load-container"><div class="loader"></div></div>
        <header>
            <nav class="navbar fixed-top navbar-dark bg-faded navbar-expand-md">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand brand" href="/">Newb</a>
                <div class="collapse navbar-collapse" id="navbar">
                {% with request.resolver_match.url_name as url_name %}
                    <ul class="navbar-nav mr-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item right-menu{% if url_name == 'account' %} active{% endif %}">
                                <a class="nav-link my-account" href="{% url 'shop:account' %}"><i class="icon-user"></i><span>Mon compte</span></a>
                                <a class="nav-link logout" href="{% url 'shop:signout' %}"><i class="icon-off"></i></a>
                            </li>
                        {% else %}
                            <li class="nav-item right-menu{% if url_name == 'login' %} active{% endif %}">
                                <a class="nav-link login" href="{% url 'shop:login' %}"><i class="icon-user"></i><span>Connexion</span></a>
                            </li>
                        {% endif %}
                        <li class="nav-item{% if url_name == 'shop' %} active{% endif %}">
                            <a class="nav-link" href="{% url 'shop:shop' %}"><i class="icon-shopping-bag"></i><span>Boutique</span></a>
                        </li>
                        <li class="nav-item{% if url_name == 'contact' %} active{% endif %}">
                            <a class="nav-link" href="{% url 'shop:contact' %}"><i class="icon-mail"></i><span>Contact</span></a>
                        </li>
                    </ul>
                {% endwith %}
                </div>
            </nav>
        </header>

        <div class="page">
            <div class="page-inner container">
                {% block page %}{% endblock page %}
            </div>
        </div>

        <footer>
            <div class="footer-inner container">
                <div class="footer-header brand">Newb</div>
                <div class="footer-name">Tiffany Haumey & Baptiste Rouxel</div>
                <div class="footer-date">UFA-4A / 2017</div>
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
        <script type="text/javascript">
            // loading animation
            $(window).on('load', function () {
                $('.load-container').fadeOut(400, function () {
                    $('body').removeClass('loading');
                    $('.load-container').remove();
                });
            });

            var $nav = $('header > nav');
            $nav.on('show.bs.collapse', function () {
                $(this).addClass('show');
            });
            $nav.on('hide.bs.collapse', function () {
                $(this).removeClass('show');
            });

            // add _blank on external links
            $.expr[':'].external = function(obj){
                return !obj.href.match(/^mailto\:/)
                       && (obj.hostname != location.hostname)
                       && !obj.href.match(/^javascript\:/)
                       && !obj.href.match(/^$/)
            };
            $('a:external').attr('target', '_blank');

            // footer fix when modal opened
            scrollbarWidth = function () {
                var parent, child, width;

                if (width === undefined) {
                    parent = $('<div style="width:50px;height:50px;overflow:auto"><div/></div>').appendTo('body');
                    child = parent.children();
                    width = child.innerWidth() - child.height(99).innerWidth();
                    parent.remove();
                }

                return width;
            };

            var $modal = $('.modal');
            var $page = $('.page');
            var $footer = $('footer');
            $modal.on('show.bs.modal', function () {
                var padding = scrollbarWidth();
                $page.css('padding-right', padding);
                $footer.css('padding-right', padding);
            });
            $modal.on('hidden.bs.modal', function () {
                $page.css('padding-right', 0);
                $footer.css('padding-right', 0);
            })
        </script>
        {% endspaceless %}{% render_block 'js' %}{% spaceless %}
    </body>
</html>
{% endspaceless %}

newb/templates/form_default.html
{% for field in form %}
    <div class="form-group row">
        <label for="{{ field.id_for_label }}" class="col-md-12 col-form-label">{{ field.label }}</label>
        <div class="col-md-12">
            {{ field }}
            <small id="help-text" class="form-text text-muted">{{ field.help_text|safe }}</small>
            {% if field.errors %}
                <div class="alert alert-danger">
                    {% if field.errors|length > 1 %}
                        <ul>
                            {% for error in field.errors %}
                                <li><strong>{{ error|escape }}</strong></li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        {% for error in field.errors %}
                            <strong>{{ error|escape }}</strong>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
{% endfor %}

newb/templates/form_inline.html
{% for field in form %}
    <div class="form-group row">
        <label for="{{ field.id_for_label }}" class="col-md-2 col-form-label">{{ field.label }}</label>
        <div class="col-md-10">
            {{ field }}
            <small id="help-text" class="form-text text-muted">{{ field.help_text|safe }}</small>
            {% if field.errors %}
                <div class="alert alert-danger">
                    {% if field.errors|length > 1 %}
                        <ul>
                            {% for error in field.errors %}
                                <li><strong>{{ error|escape }}</strong></li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        {% for error in field.errors %}
                            <strong>{{ error|escape }}</strong>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
{% endfor %}

newb/templates/index.html
{% extends 'base.html' %}
{% load sekizai_tags static %}

{% block page %}
    {% addtoblock 'css' %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    {% endaddtoblock %}

    <div class="bg"></div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                Hoc inmaturo interitu ipse quoque sui pertaesus excessit e vita aetatis nono anno atque vicensimo cum quadriennio imperasset. natus apud Tuscos in Massa Veternensi, patre Constantio Constantini fratre imperatoris, matreque Galla sorore Rufini et Cerealis, quos trabeae consulares nobilitarunt et praefecturae.
            </div>
        </div>
    </div>
{% endblock %}