newb/apps/shop/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from newb.apps.shop import views
from newb.apps.shop.forms import AuthForm

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^shop/$', views.shop, name='shop'),
    url(r'^shop/checkout/(?P<id>[0-9]+)/$', views.shop_checkout, name='shop_checkout'),
    url(r'^shop/checkout/done/$', views.shop_checkout_done, name='shop_checkout_done'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='shop/login.html', authentication_form=AuthForm), name='login'),
    url(r'^authentication/$', views.authentication, name='authentication'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^account/$', views.account, name='account'),
    url(r'^contact/$', views.contact, name='contact'),
]

newb/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from newb import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('newb.apps.shop.urls', namespace='shop')),
    url('^', include('django.contrib.auth.urls')),  # keep at the end
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newb/apps/shop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField


class Genre(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nom')

    def __str__(self):
        return self.name


class Platform(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nom')
    constructor = models.CharField(max_length=100, null=True, blank=True, verbose_name='Constructeur')
    release_year = models.IntegerField(null=True, blank=True, verbose_name='Année de sortie')

    def __str__(self):
        return self.name


class Editor(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nom')

    def __str__(self):
        return self.name


class Developer(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nom')

    def __str__(self):
        return self.name


class VideoGame(models.Model):
    title = models.CharField(max_length=200, verbose_name='Titre')
    release_date = models.DateField(null=True, blank=True, verbose_name='Date de sortie')
    genres = models.ManyToManyField('Genre', verbose_name='Genres')
    platforms = models.ManyToManyField('Platform', verbose_name='Plateformes')
    editor = models.ForeignKey('Editor', verbose_name='Éditeur', null=True, blank=True)
    developer = models.ForeignKey('Developer', verbose_name='Développeur')
    picture = models.ImageField(upload_to="media/uploaded/img/shop/", null=True, blank=True, verbose_name='Jaquette')
    description = models.TextField(null=True, verbose_name='Description')
    price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Prix')

    def __str__(self):
        return self.title


# we add some informations at the user model which already exist on django
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=150, verbose_name='Adresse')
    postal_code = models.CharField(max_length=5, verbose_name='Code postal')
    city = models.CharField(max_length=100, verbose_name='Ville')
    country = models.CharField(max_length=75, verbose_name='Pays')
    phone = PhoneNumberField(verbose_name='Numéro de téléphone', help_text='Avec l\'indicatif du pays.')

    def __str__(self):
        return self.user


@receiver(post_save, sender=User)
def update_user_customer(sender, instance, created, **kwargs):
    if created:
        Customer.objects.create(user=instance)
    instance.customer.save()


class Contact(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nom')
    email = models.EmailField(verbose_name='Adresse email')
    subject = models.CharField(max_length=150, verbose_name='Sujet')
    message = models.TextField(verbose_name='Message')

    def __str__(self):
        return self.name + ' > [' + self.subject + "] " + self.message


class Order(models.Model):
    customer = models.ForeignKey("Customer")
    item = models.ForeignKey("VideoGame")

newb/apps/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from newb.apps.shop.models import Contact, Customer


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class CustomerRegisterForm(forms.ModelForm):

    class Meta:
        model = Customer
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(CustomerRegisterForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs.update({'placeholder': '+33'})
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class AuthForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(AuthForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

newb/apps/shop/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from newb.apps.shop.forms import CustomerRegisterForm, ContactForm, UserRegisterForm
from .models import VideoGame, Order


def index(request):
    context = {}
    return render(request, 'shop/index.html', context)


def shop(request):
    context = {
        'products': VideoGame.objects.all()
    }
    return render(request, 'shop/shop.html', context)


@login_required(login_url='/login/')
def shop_checkout(request, id):
    context = {
        'product': VideoGame.objects.get(id=id)
    }
    return render(request, 'shop/shop_checkout.html', context)


@login_required(login_url='/login/')
def shop_checkout_done(request):
    if request.method == 'POST':
        product = VideoGame.objects.get(id=request.POST.get("product-id"))
        order = Order(customer=request.user.customer, item=product)
        order.save()
        return redirect('shop:account')

    return redirect('shop:index')


def authentication(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)

    if user is not None:
        login(request, user)
        return HttpResponseRedirect('/')

    else:
        return HttpResponseRedirect('/login/')


@login_required(login_url='/login/')
def signout(request):
    logout(request)
    return HttpResponseRedirect('/')


@transaction.atomic
def register(request):
    if request.method == 'POST':
        user_form = UserRegisterForm(request.POST, prefix="user_form")
        customer_form = CustomerRegisterForm(request.POST, prefix="customer_form")

        if user_form.is_valid() and customer_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()

            user.customer.user_id = user.id
            user.customer.address = customer_form.cleaned_data.get('address')
            user.customer.postal_code = customer_form.cleaned_data.get('postal_code')
            user.customer.city = customer_form.cleaned_data.get('city')
            user.customer.country = customer_form.cleaned_data.get('country')
            user.customer.phone = customer_form.cleaned_data.get('phone')

            user.save()

            raw_password = user_form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')

    else:
        user_form = UserRegisterForm()
        user_form.prefix = "user_form"
        customer_form = CustomerRegisterForm()
        customer_form.prefix = "customer_form"

    context = {'user_form': user_form, 'customer_form': customer_form}
    return render(request, 'shop/register.html', context)


@login_required(login_url='/login/')
def account(request):
    context = {
        'orders': Order.objects.filter(customer=request.user.customer),
    }
    return render(request, 'shop/account.html', context)


def contact(request):
    context = {}
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            contact_instance = form.save()
            contact_instance.name = form.cleaned_data.get('name')
            contact_instance.subject = form.cleaned_data.get('subject')
            contact_instance.message = form.cleaned_data.get('message')
            contact_instance.save()

            if contact_instance is not None:
                context['success'] = "Message envoyé !"
                form = ContactForm()

    else:
        form = ContactForm()

    context['form'] = form
    return render(request, 'shop/contact.html', context)

newb/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'index.html', context)

newb/templates/shop/account.html
{% extends 'base.html' %}
{% load sekizai_tags static sass_tags %}

{% block title %}Mon compte{% endblock %}
{% block page %}
    <div class="card-container">
        <div class="row">
            <div class="col-md-12"><h1>{{ request.user.first_name }} {{ request.user.last_name }}</h1></div>
        </div><br/>
        <div class="row">
            <div class="col-md-2"><b>Email</b></div>
            <div class="col-md-10">{{ request.user.email }}</div>
        </div>
        <div class="row">
            <div class="col-md-2"><b>Téléphone</b></div>
            <div class="col-md-10">{{ request.user.customer.phone }}</div>
        </div>
        <div class="row">
            <div class="col-md-2"><b>Adresse</b></div>
            <div class="col-md-10">{{ request.user.customer.address }}</div>
        </div>
        <div class="row">
            <div class="col-md-2"><b>Code postal</b></div>
            <div class="col-md-10">{{ request.user.customer.postal_code }}</div>
        </div>
        <div class="row">
            <div class="col-md-2"><b>Ville</b></div>
            <div class="col-md-10">{{ request.user.customer.city }}</div>
        </div>
        <div class="row">
            <div class="col-md-2"><b>Pays</b></div>
            <div class="col-md-10">{{ request.user.customer.country }}</div>
        </div>
    </div>

    <div class="card-container margin-top">
        <h1>Achats</h1><br/>
        {% if orders %}
            {% for order in orders %}
                <div class="row">
                    <div class="col-12">{{ order.item.title }} - {{ order.item.price }} €</div>
                </div>
            {% endfor %}
        {% else %}
            <span>Aucun achat effectué.</span>
        {% endif %}
    </div>
{% endblock %}

newb/templates/shop/contact.html
{% extends 'base.html' %}
{% load sekizai_tags static sass_tags %}

{% block title %}Contact{% endblock %}
{% block page %}
    {% if success %}
        <div class="alert alert-success" role="alert">{{ success }}</div>
    {% endif %}
    <form action="{% url 'shop:contact' %}" method="post">
        {% csrf_token %}
        {% include 'form_inline.html' %}
         <div class="row justify-content-end">
             <div class="col-md-10 text-center"><input class="btn btn-info" type="submit" value="Valider"/></div>
         </div>
    </form>
{% endblock %}

newb/templates/shop/index.html
{% extends 'base.html' %}
{% load sekizai_tags static sass_tags %}

{% block title %}Accueil{% endblock %}
{% block page %}
    {% addtoblock 'css' %}<link rel="stylesheet" type="text/css" href="{% sass_src 'css/shop/index.scss' %}">{% endaddtoblock %}

    <div class="home-text">
        <div>Les&nbsp;meilleurs&nbsp;jeux, au&nbsp;meilleur&nbsp;prix, c'est&nbsp;ici.</div>
        <button type="button" class="btn btn-info btn-lg" onclick="window.location.href='{% url 'shop:shop' %}'">Parcourir la boutique</button>
    </div>

    {% addtoblock "js" %}
        <script type="text/javascript">
            $(document).ready(function () {
                var scroll = 0;
                var header = $('header > nav');
                var headerHeight = header.height();

                function menuBehavior() {
                    scroll = $(this).scrollTop();
                    if (scroll > headerHeight/2) {
                        header.addClass('scrolled');
                    } else {
                        header.removeClass('scrolled');
                    }
                }

                menuBehavior();
                $(document).scroll(function () {
                    menuBehavior();
                });
                header.addClass('visible');
                header.show();
            });
        </script>
    {% endaddtoblock %}
{% endblock %}

newb/templates/shop/login.html
{% extends 'base.html' %}
{% load sekizai_tags static sass_tags %}

{% block title %}Connexion{% endblock %}
{% block page %}
    <div class="login-container">
        {% if form.errors %}
            <p>Votre identifiant et mot de passe ne correspondent pas. Veuillez réessayer.</p>
        {% endif %}

        {% if next %}
            {% if user.is_authenticated %}
                <p>Votre compte n'a pas le droit d'accéder à cette page. Pour continuer, veuillez vous connecter avec un compte qui dispose des droits.</p>
            {% else %}
                <p>Veuillez vous connecter pour voir cette page.</p>
            {% endif %}
        {% endif %}

        <form method="post" action="{% url 'shop:authentication' %}">
            {% csrf_token %}
            {% include 'form_default.html' %}

            <div class="row justify-content-end">
                <div class="col-md-12 text-center">
                    <input class="btn btn-info" type="submit" value="Valider"/>&nbsp;
                    <input class="btn btn-secondary" type="button" value="Inscription" onclick="window.location.href='{% url 'shop:register' %}'"/>
                </div>
                <div class="col-md-12 text-center">
                    <a href="{% url 'password_reset' %}">Mot de passe oublié ?</a>
                </div>
            </div>

            <input type="hidden" name="next" value="{{ next }}"/>
        </form>
    </div>
{% endblock %}

newb/templates/shop/products.html
{% extends 'base.html' %}
{% load sekizai_tags static sass_tags %}

{% block title %}Produits{% endblock %}
{% block page %}
    {% addtoblock 'css' %}
        <link rel="stylesheet" type="text/css" href="{% sass_src 'css/shop/products.scss' %}">
    {% endaddtoblock %}

    <ul class="products-list row">
        {% for product in products %}
            <li class="list-item col-xl-3 col-md-4 col-sm-6 col-12">
                <button type="button" class="not-really-a-button product" data-toggle="modal" data-target="#modal-{{ product.id }}">
                    <div class="product-picture">{% if product.picture %}<img height="200px" src="{{ product.picture }}" />{% else %}<span class="picture-placeholder">?</span>{% endif %}</div>
                    <div class="product-title"><span>{{ product.title }}</span></div>
                    <div class="product-price"><span>{{ product.price }} €</span></div>
                </button>
                <div class="modal fade" id="modal-{{ product.id }}" tabindex="-1" role="dialog" aria-labelledby="modal-{{ product.id }}-label" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="modal-{{ product.id }}-label">{{ product.title }}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body product-details">
                                {% if product.picture %}<div class="product-picture-bg" style="background-image: url('{{ product.picture }}')"></div>{% endif %}
                                <div class="product-table-container">
                                    <table class="table">
                                        <tbody>
                                            <tr>
                                                <th>Date de sortie</th>
                                                <td>{% if product.release_date %}{{ product.release_date }}{% else %}À déterminer{% endif %}</td>
                                            </tr>
                                            <tr>
                                                <th>Genre{% if product.genres.all|length > 1 %}s{% endif %}</th>
                                                <td>{% for genre in product.genres.all %}{{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                                            </tr>
                                            <tr>
                                                <th>Plateforme{% if product.platforms.all|length > 1 %}s{% endif %}</th>
                                                <td>{% for platform in product.platforms.all %}{{ platform }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                                            </tr>
                                            <tr>
                                                <th>Éditeur</th>
                                                <td>{% if product.editor %}{{ product.editor }}{% else %}Non précisé{% endif %}</td>
                                            </tr>
                                            <tr>
                                                <th>Développeur</th>
                                                <td>{{ product.developer }}</td>
                                            </tr>
                                            <tr>
                                                <td colspan="2"><b>Description</b>{{ product.description }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-info">Acheter - {{ product.price }} €</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

newb/templates/shop/register.html
{% extends 'base.html' %}
{% load sekizai_tags static sass_tags %}

{% block title %}Inscription{% endblock %}
{% block page %}
    <form action="{% url 'shop:register' %}" method="post">
        {% csrf_token %}
        {% include 'form_inline.html' with form=user_form %}
        <div class="hr margin"></div>
        {% include 'form_inline.html' with form=customer_form %}
        <div class="row justify-content-end">
             <div class="col-md-10 text-center"><input class="btn btn-info" type="submit" value="Valider" /></div>
         </div>
    </form>
{% endblock %}

newb/templates/shop/shop.html
{% extends 'base.html' %}
{% load sekizai_tags static sass_tags %}

{% block title %}Produits{% endblock %}
{% block page %}
    {% addtoblock 'css' %}<link rel="stylesheet" type="text/css" href="{% sass_src 'css/shop/products.scss' %}">{% endaddtoblock %}

    <ul class="products-list row">
        {% for product in products %}
            <li class="list-item col-xl-3 col-md-4 col-sm-6 col-12">
                <button type="button" class="not-really-a-button product card-container" data-toggle="modal" data-target="#modal-{{ product.id }}">
                    <div class="product-picture">{% if product.picture %}<img height="200px" src="{{ product.picture }}" />{% else %}<span class="picture-placeholder">?</span>{% endif %}</div>
                    <div class="product-title"><span>{{ product.title }}</span></div>
                    <div class="product-price"><span>{{ product.price }} €</span></div>
                </button>
                <div class="modal fade" id="modal-{{ product.id }}" tabindex="-1" role="dialog" aria-labelledby="modal-{{ product.id }}-label" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="modal-{{ product.id }}-label">{{ product.title }}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body product-details">
                                {% if product.picture %}<div class="product-picture-bg" style="background-image: url('{{ product.picture }}')"></div>{% endif %}
                                <div class="product-table-container">
                                    <table class="table">
                                        <tbody>
                                            <tr>
                                                <th>Date de sortie</th>
                                                <td>{% if product.release_date %}{{ product.release_date }}{% else %}À déterminer{% endif %}</td>
                                            </tr>
                                            <tr>
                                                <th>Genre{% if product.genres.all|length > 1 %}s{% endif %}</th>
                                                <td>{% for genre in product.genres.all %}{{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                                            </tr>
                                            <tr>
                                                <th>Plateforme{% if product.platforms.all|length > 1 %}s{% endif %}</th>
                                                <td>{% for platform in product.platforms.all %}{{ platform }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                                            </tr>
                                            <tr>
                                                <th>Éditeur</th>
                                                <td>{% if product.editor %}{{ product.editor }}{% else %}Non précisé{% endif %}</td>
                                            </tr>
                                            <tr>
                                                <th>Développeur</th>
                                                <td>{{ product.developer }}</td>
                                            </tr>
                                            <tr>
                                                <td colspan="2"><b>Description</b>{{ product.description }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-info" onclick="window.location.href='{% if user.is_authenticated %}{% url 'shop:shop_checkout' product.id %}{% else %}{% url 'shop:login' %}{% endif %}'">Acheter - {{ product.price }} €</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

newb/templates/shop/shop_checkout.html
{% extends 'base.html' %}
{% load sekizai_tags static sass_tags %}

{% block title %}Confirmation de l'achat{% endblock %}
{% block page %}
    <form class="card-container" action="{% url 'shop:shop_checkout_done' %}" method="post">
        {% csrf_token %}

        <div class="row text-center">
            <div class="col-12">Voulez-vous vraiment acheter {{ product.title }} ?</div>
        </div><br/>
        <div class="col-md-12 text-center">
            <input type="hidden" name="product-id" value="{{ product.id }}">
            <input class="btn btn-info" type="submit" value="Valider - {{ product.price }} €"/>&nbsp;
            <input class="btn btn-secondary" type="button" value="Annuler" onclick="window.location.href='{% url 'shop:index' %}'"/>
        </div>
    </form>
{% endblock %}

newb/templates/shop/shop_checkout_done.html
{% extends 'base.html' %}
{% load sekizai_tags static sass_tags %}

{% block title %}Achat effectué{% endblock %}
{% block page %}

{% endblock %}